addStudent: SUCCESS
addCourse: SUCCESS
addStudent: SUCCESS
removeStudent: FAILURE
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
getStudentPoints: SUCCESS, 0
enrollStudent: SUCCESS
awardAcademicPoints: INVALID_INPUT
enrollStudent: FAILURE
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
removeStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addCourse: SUCCESS
removeCourse: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
getStudentPoints: FAILURE
addStudent: SUCCESS
enrollStudent: SUCCESS
addCourse: SUCCESS
addCourse: SUCCESS
addCourse: SUCCESS
enrollStudent: FAILURE
addStudent: SUCCESS
getStudentPoints: SUCCESS, 0
removeCourse: SUCCESS
enrollStudent: SUCCESS
removeCourse: SUCCESS
addStudent: SUCCESS
removeStudent: SUCCESS
completeCourse: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
awardAcademicPoints: SUCCESS
completeCourse: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
awardAcademicPoints: SUCCESS
completeCourse: SUCCESS
removeStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
completeCourse: SUCCESS
removeStudent: SUCCESS
getStudentPoints: SUCCESS, 7
addStudent: SUCCESS
removeStudent: SUCCESS
awardAcademicPoints: INVALID_INPUT
enrollStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: FAILURE
awardAcademicPoints: SUCCESS
addCourse: SUCCESS
enrollStudent: SUCCESS
addCourse: FAILURE
addStudent: SUCCESS
awardAcademicPoints: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
removeStudent: FAILURE
getStudentPoints: SUCCESS, 13
enrollStudent: FAILURE
addStudent: SUCCESS
addStudent: SUCCESS
awardAcademicPoints: SUCCESS
enrollStudent: INVALID_INPUT
addStudent: SUCCESS
getStudentPoints: SUCCESS, 0
removeStudent: SUCCESS
addStudent: FAILURE
awardAcademicPoints: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: INVALID_INPUT
enrollStudent: FAILURE
addStudent: SUCCESS
enrollStudent: SUCCESS
addCourse: SUCCESS
enrollStudent: FAILURE
addStudent: SUCCESS
addStudent: SUCCESS
completeCourse: SUCCESS
completeCourse: SUCCESS
removeStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: INVALID_INPUT
enrollStudent: SUCCESS
addStudent: FAILURE
addStudent: SUCCESS
completeCourse: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
removeStudent: SUCCESS
addStudent: SUCCESS
addCourse: FAILURE
enrollStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
completeCourse: FAILURE
enrollStudent: SUCCESS
enrollStudent: SUCCESS
awardAcademicPoints: SUCCESS
addCourse: SUCCESS
awardAcademicPoints: SUCCESS
addCourse: SUCCESS
enrollStudent: SUCCESS
addCourse: SUCCESS
addCourse: INVALID_INPUT
getStudentPoints: SUCCESS, 29
addStudent: SUCCESS
enrollStudent: SUCCESS
addCourse: FAILURE
addStudent: FAILURE
removeStudent: SUCCESS
addCourse: INVALID_INPUT
enrollStudent: SUCCESS
addStudent: SUCCESS
addStudent: FAILURE
completeCourse: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: INVALID_INPUT
enrollStudent: FAILURE
addCourse: INVALID_INPUT
enrollStudent: SUCCESS
completeCourse: SUCCESS
enrollStudent: FAILURE
completeCourse: SUCCESS
addCourse: SUCCESS
addStudent: INVALID_INPUT
enrollStudent: FAILURE
addStudent: FAILURE
addStudent: FAILURE
awardAcademicPoints: SUCCESS
awardAcademicPoints: SUCCESS
getStudentPoints: SUCCESS, 24
addStudent: FAILURE
getStudentPoints: SUCCESS, 19
enrollStudent: SUCCESS
awardAcademicPoints: SUCCESS
completeCourse: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
addCourse: FAILURE
completeCourse: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
completeCourse: SUCCESS
completeCourse: SUCCESS
enrollStudent: SUCCESS
getStudentPoints: SUCCESS, 39
enrollStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
removeStudent: SUCCESS
addCourse: SUCCESS
addStudent: INVALID_INPUT
completeCourse: SUCCESS
addStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: FAILURE
getStudentPoints: SUCCESS, 20
addStudent: SUCCESS
addStudent: FAILURE
completeCourse: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
addCourse: SUCCESS
completeCourse: SUCCESS
addCourse: SUCCESS
awardAcademicPoints: SUCCESS
completeCourse: SUCCESS
enrollStudent: SUCCESS
completeCourse: SUCCESS
getStudentPoints: FAILURE
enrollStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: FAILURE
awardAcademicPoints: SUCCESS
addCourse: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
completeCourse: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
completeCourse: SUCCESS
addStudent: SUCCESS
removeStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
enrollStudent: SUCCESS
getStudentPoints: SUCCESS, 48
addStudent: SUCCESS
addStudent: SUCCESS
addStudent: FAILURE
getStudentPoints: SUCCESS, 36
addCourse: SUCCESS
addStudent: SUCCESS
removeStudent: SUCCESS
addCourse: SUCCESS
addStudent: FAILURE
enrollStudent: SUCCESS
enrollStudent: SUCCESS
addCourse: INVALID_INPUT
removeStudent: SUCCESS
completeCourse: SUCCESS
enrollStudent: SUCCESS
addStudent: SUCCESS
completeCourse: SUCCESS
addStudent: SUCCESS
enrollStudent: SUCCESS
removeStudent: SUCCESS
addStudent: FAILURE
enrollStudent: FAILURE
completeCourse: SUCCESS
awardAcademicPoints: SUCCESS
addStudent: SUCCESS
